package main.visualiser;

import server.Server;
import server.User;
import server.UserHistory;

import javax.swing.*;
import java.util.ArrayList;

public class Leaderboard extends JFrame {


    public Leaderboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public String getAllTime(){

        ArrayList<User> database = Server.getUserDatabase();

        double best = 0;
        User bestUs = null;

        for(User user : database){


            double sum = 0;

            if(user.getHistoricalData().size() == 0){
                continue;
            }

            for(UserHistory his : user.getHistoricalData()){
                sum += his.getEnergyUsed() / user.getHistoricalData().size();
            }

            if(sum < best || bestUs == null){
                best = sum;
                bestUs = user;
            }

        }

        return bestUs.getUsername();

    }

    public String getWeek(){

        ArrayList<User> database = Server.getUserDatabase();

        double best = 0;
        User bestUs = null;

        for(User user : database){


            if(user.getHistoricalData().size() == 0){
                continue;
            }

            double sum = 0;
            for(int i = user.getHistoricalData().size()-1; i < user.getHistoricalData().size()-8; i++){
                if(i < 0){
                    break;
                }
                int div = user.getHistoricalData().size();
                if(div > 7){
                    div = 7;
                }
                sum += user.getHistoricalData().get(i).getEnergyUsed() / div;
            }

            if(sum < best || bestUs == null){
                best = sum;
                bestUs = user;
            }

        }

        return bestUs.getUsername();
    }

    public String getToday(){
        ArrayList<User> database = Server.getUserDatabase();

        double best = 0;
        User bestUs = null;

        for(User user : database){

             if(user.getHistoricalData().size() == 0){
                 continue;
             }

             double sum = user.getHistoricalData().get(0).getEnergyUsed();
             if(user.getHistoricalData().size() > 1) {
                 sum = user.getHistoricalData().get(user.getHistoricalData().size() - 1).getEnergyUsed();
             }
            if(sum < best || bestUs == null){
                best = sum;
                bestUs = user;
            }

        }

        return bestUs.getUsername();
    }

    public String getMostImproved(){

        ArrayList<User> database = Server.getUserDatabase();

        double best = 0;
        User bestUs = null;

        for(User user : database){

            if(user.getHistoricalData().size() == 0){
                continue;
            }

            double first = user.getHistoricalData().get(0).getEnergyUsed();
            double change = 0;

            for(int i = 0; i < user.getHistoricalData().size(); i++){

                double difference = first - user.getHistoricalData().get(i).getEnergyUsed();
                if(difference > 0){
                    change = difference;
                }
                first = user.getHistoricalData().get(i).getEnergyUsed();

            }

            if(change < best || bestUs == null){
                best = change;
                bestUs = user;
            }

        }

        return bestUs.getUsername();
    }


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Top Energy Savers");

        jLabel2.setText("All Time Best:");

        jLabel3.setText("Top This Week:");

        jLabel4.setText("Top Today:");

        jLabel5.setText("Most Improved:");

        jLabel6.setText(getAllTime());

        jLabel7.setText(getWeek());

        jLabel8.setText(getToday());

        jLabel9.setText(getMostImproved());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)))
                                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration

}
